---

version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:

  test:

    docker:
      - image: bdockerimg/bmakelib:opensuse-tumbleweed
        environment:
          LANG: en_US.UTF-8
    resource_class: medium

    working_directory: ~/prolog-etudes

    steps:

      - run:
          name: Install the runtime
          command: >-
            zypper --non-interactive refresh
            && zypper --non-interactive install swipl

      - checkout

      - run:
          name: Run the tests
          command: >-
            make test-coverage-report=yes test

      - codecov/upload:
          file: ".coverage"

workflows:
  build_test:
    jobs:
      - test
